# Site Settings
title: "Dawson Gardels" #
description: "My website" #
url: "https://dawson-git.github.io" #

# Author Information (Sidebar/Profile)
author:
  name: "Dawson Gardels" #
  avatar: "https://static.wikia.nocookie.net/metroid/images/8/8c/SSB_Ultimate_Samus_render.png/revision/latest/scale-to-width-down/290?cb=20180612174025"
  bio: "From Idaho Falls" #
  location: "Boise, ID"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com" #

# Interests Section
interests: #
  - item: "Games" #
  - item: "Fixing things" #

# External Links / Cool Sites
cool_sites: #
  - title: "GitHub"
    url: "https://github.com" #
  - title: "Metroid Wiki"
    url: "https://metroid.fandom.com/wiki/Metroid_Wiki" #

theme: jekyll-theme-minimal
